### ISSUE TITLE
Not working with Foundry v11

### ISSUE THREAD

**Issue by Storebrorsan** [kbender84/coriolis-kbender-ships#1]
Hi, new fan of your content here :)
I noticed that the module wasn’t working with v11. Only require some small fixes thought in the module.json
Can I upload you the corrected file somewhere? (New on github..)

**Comment by kbender84** [comment]
Thanks for noticing!

I need to push latest code, it is older than packed in release file.
I will take a look, but if you already have the updated file, you can post it here and I will include it.

And I need to change the readme file as well.

**Comment by Storebrorsan** [comment]
{
  "id": "coriolis-kbender-ships",
  "title": "Coriolis kbender ships pack",
  "description": "Ships scenes for Coriolis RPG",
  "version": "0.4",
  "authors": [
    {
      "name": "benderworks",
      "url": "https://www.patreon.com/benderworks/about",
      "discord": "kbender#0388",
      "flags": {}
    }
  ],
  "compatibility": {
    "minimum": "10",
    "verified": "11"
  },
  "relationships": {
    "systems": [
      {
        "id": "yzecoriolis",
        "type": "system",
        "manifest": "https://github.com/winks-vtt/yze-coriolis/releases/latest/download/system.json",
        "compatibility": {
          "verified": "3.0.5"
        }
      }
    ]
  },
  "packs": [
    {
      "name": "coriolis-kbender-ships",
      "system": "yzecoriolis",
      "label": "Coriolis kbender ships",
      "path": "packs/coriolis-kbender-ships",
      "type": "Scene",
      "ownership": {
        "PLAYER": "OBSERVER",
        "ASSISTANT": "OWNER"
      },
      "flags": {}
    }
  ],
  "manifest": "https://github.com/kbender84/coriolis-kbender-ships/releases/download/0.4/module.json",
  "download": "https://github.com/kbender84/coriolis-kbender-ships/releases/download/0.4/coriolis-kbender-ships.zip"
}

**Comment by Storebrorsan** [comment]
Here is the code, I wasn't able to post the file :)

The things I changed:
1. "name" to "id" in second line.
2. adding the "compatibility" lines (I think it was "verified" that was missing, but I just switched this full section as I used the Emissary lost module as my cheat sheet :) )
3. adding "relationships" with "systems" for the pack(s)
4. Also I changed from 0.1 to 0.4 in the link to the manifest

**Comment by kbender84** [comment]
Thanks. I need to rethink now what should I do with this repo. I am using it to provide premium content for my Patreon. For now I will leave it as is, but I may discontinue support or make it private in future.

Right now 0.5 is available, I need to push the code to GitHub :)

https://github.com/kbender84/coriolis-kbender-ships/releases/download/0.5/module.json

**Comment by kbender84** [comment]
Also, there is v5 already uploaded under 

https://github.com/kbender84/coriolis-kbender-ships/releases/download/0.5/module.json

**Comment by Storebrorsan** [comment]
Oh sorry, I’m yet to subscribe for a patreon level and I didn’t realize that 0.1 in the json could be a feature and not a bug! :)
Thanks for 0.5 !
